### ISSUE TITLE
Heartbeat implementieren

### ISSUE THREAD

**Issue by cybre-finn** [cybre-finn/VSP#12]

**Comment by cybre-finn** [comment]
Muss Serverseitig implementiert werden. Muss durch client iniitiert werden.

**Comment by cybre-finn** [comment]
Müsste man imho in einem seperaten Thread behandeln, sowohl auf server,als auch auf client seite. Hier auch darauf achten, dass wir evtl. irgendwie eine laufende aktion abbrechen können müssen bzw. den aktuellen befehl verwerfen...

**Comment by Twhyzer** [comment]
Heartbeat ist implementiert. Bitte um Review @cybre-finn.

**Comment by cybre-finn** [comment]
Review

**Comment by cybre-finn** [comment]
- Warum Heartbeat message ein String? Könnte auch ne Zahl sein. 
- Warum Observer/Callback Verzeichnisse im Paket application? Können die nicht ein eigenes bekommen? Heartback-Callback wird z.B. nur von HB genutzt und ist nichtmal wirklich in Application.
