### ISSUE TITLE
Checkliste Abgabe Dokumentation

### ISSUE THREAD

**Issue by cybre-finn** [cybre-finn/VSP#19]
# Arc42
- [x] Lösungsstrategie anpassen
- [x] Texte für Bausteinsicht
- [x] Verteilungssicht
- [x] Querschnittliche Konzepte
- [x] Qualitätsanforderung
- [x] Risiken & Technische Schulden
- [x] Application überarbeiten? -> Finn

**Comment by Twhyzer** [comment]
Erfolgreich abgegeben.
