### ISSUE TITLE
Fix weird behavior of RESTFul GUI substitute

### ISSUE THREAD

**Issue by cybre-finn** [cybre-finn/VSP#25]
Easy to reproduce - use the example requests in the README via curl. You will see that the robot does not really move in all directions - sometimes it moves in multiple directions, even though only one servo was changed. Sometimes nothing moves.

ideas:
- Is it purely an issue of the RESTful implementation? Could be timing in comm
- probably something with the swith statement used, if it's the RESTful interface

**Comment by Twhyzer** [comment]
You need break-statements in your switch case
