### ISSUE TITLE
Application-Stub überdenken/Recherche 

### ISSUE THREAD

**Issue by cybre-finn** [cybre-finn/VSP#8]
Evtl. müssen Teile der Application neu designed werden.
Wir wissen noch nicht ganz, was der Application Stub genau macht, ob wir ihn überhaupt brauchen.

Vermutungen:
- Der App Stub ist fürs Testen/Simulieren
- Der App Stub dient als Zwischenschicht, um ein via Observer-Pattern realisiertes MVC verteilen zu können.

**Comment by cybre-finn** [comment]
Becke hat gesagt, der App Stub ist nötig, wird auf Seite 77 van Steen genauer beschrieben.

**Comment by cybre-finn** [comment]
Lese morgen im van Steen nach, wenn ichs schaff

**Comment by Twhyzer** [comment]
Observer Pattern ist mittlerweile veraltet. Es werden Callback-Funktionen benutzt.
Grundlegende Verteilung ohne ApplicationStub ist implementiert. Benötigen noch weitere Informationen zur Realisierung.

**Comment by cybre-finn** [comment]
Also, ich habe rausgefunden, wofür der Application Stub ist. @Twhyzer  hattest nicht ganz unrecht mit dem Testen, evtl. meintest du auch genau die Sache und ich habs einfach nicht gerafft.

Wenn ich es richtig verstanden hab, dann ist der App Stub dafür da, einfach nur die Interfaces existierender Klassen nachzubilden und für bestimmte Funktionen dann eben Verteilung anzubieten. Mit anderen Worten: Wenn ich in der Standalone direkt die Methode x am "Klasseninterface" vom Model aufrufe, so ersetze ich in der verteilten Anwendung genau das durch ein entsprechendes Interface, bzw. einen Wrapper, der das ursprüngliche Interface in Calls an den Client Stub übersetzt. An der Stelle könnte man natürlich auch Dinge kapseln, die eigentlich nicht in der Ursprünglichen Anwendung vorkommen. Z.b. habe ich in einem anderen Ticket die Kommunikation nochmal neu bedacht und mit möglichen Callbacks versehen.

**Comment by Twhyzer** [comment]
ApplicationStubs sind implementiert.
